#!/usr/bin/env python
# -*- coding:utf-8 -*-
#Copyright 2018 SichunHao sichunh@bu.edu
import os,sys,time

def get_file_list(file_path):
	dir_list = os.listdir(file_path)
	if not dir_list:
		return
	else:
		dir_list = sorted(dir_list,key=lambda x: os.path.getmtime(os.path.join(file_path, x)))
		return(dir_list)

a = get_file_list('.')


n = int(sys.argv[1])


for i in range(0,n):
	print(a[i])



#import os,sys
def order(filename):
	"loop up modified time of filer"
	return os.stat(filename).st_mtime
L=os.listdir()
L.sort(key=order)
for f in L[:int(sys.argv[1])]:
